# Generated by Django 3.0.5 on 2020-12-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libmanage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarian',
            name='l_id',
            field=models.IntegerField(default=0),
        ),
    ]
