# Generated by Django 3.0.5 on 2021-01-04 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libmanage', '0003_auto_20210103_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('Available', 'AVAILABLE'), ('Issued', 'ISSUED')], default='Available', max_length=10),
        ),
    ]
