# Generated by Django 3.0.5 on 2021-01-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libmanage', '0004_auto_20210104_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Issued', 'Issued')], default='Available', max_length=10),
        ),
    ]
