# Generated by Django 3.0.5 on 2021-01-04 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libmanage', '0006_auto_20210105_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
    ]
